### ISSUE TITLE
Domains with a leading dot are now accepted as valid

### ISSUE THREAD

**Issue by tomhughes** [validates-email-format-of/validates_email_format_of#109]
Since 1.8.0 an address like `help@.me.uk` is considered valid when it wasn't before.

The problem seems to be #103 because of this:

```ruby
bericote [~/src/osm/rails] % bundle exec irb
irb(main):001> require "simpleidn"
=> true
irb(main):002> SimpleIDN.to_ascii(".me.uk")
=> "me.uk"
```

which causes the leading dot to get lost during the domain validation.

**Comment by alexdunae** [comment]
Thanks for such a tidy bug report and repro steps!  I've merged in the fix.  I'll let the dust settle a little and then put out a point release this week.
