### ISSUE TITLE
non-ascii characters in domain cause the validation to raise exception with check_mx: true

### ISSUE THREAD

**Issue by costa** [validates-email-format-of/validates_email_format_of#35]
"anything_like@hotmail.cô" will raise

```
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
```

which is not too good.

**Comment by steakknife** [comment]
"Borrow" ;)

I've already been down this route, hence [stringprep](https://github.com/steakknife/stringprep)* and [nameprep](https://github.com/steakknife/nameprep)* are non-trivial, hence libidn.  * = WIP.

Patches welcome! :)
