### ISSUE TITLE
Why is validate_email_domain checking for a valid A record?

### ISSUE THREAD

**Issue by jrodrigosm** [validates-email-format-of/validates_email_format_of#47]
Hi,

I found that validate_email_domain considers that a domain is valid if it has a valid MX record (of course) or if it has a valid A record.

Why is a valid A record enough to justify that the domain is valid? It is my understanding that, if the domain has no valid MX record, it won't receive any email at all. So, why consider it valid with an A record?

This is the code I'm talking about:

    def self.validate_email_domain(email)
      domain = email.to_s.downcase.match(/\@(.+)/)[1]
      Resolv::DNS.open do |dns|
        @mx = dns.getresources(domain, Resolv::DNS::Resource::IN::MX) + dns.getresources(domain, Resolv::DNS::Resource::IN::A)
      end
      @mx.size > 0 ? true : false
    end

This was introduced in this 2010 commit: https://github.com/validates-email-format-of/validates_email_format_of/commit/a2d2119c5f3588dc5d303a07b51504f6904e2256#commitcomment-8972745

Thanks!

P.S.: I commented the commit yesterday, but I decided to delete the commit comment and post this question as an issue instead.

**Comment by raszi** [comment]
:+1: I just ran into this, A record check should be removed.

**Comment by raszi** [comment]
A records should be used if no MX record could be found:

http://en.wikipedia.org/wiki/MX_record#History_of_fallback_to_address_record

**Comment by jrodrigosm** [comment]
Didn't know that, I guess next time I'll read the RFC before asking. Thanks for clarifying!
