### ISSUE TITLE
email field empty

### ISSUE THREAD

**Issue by sarovin** [validates-email-format-of/validates_email_format_of#60]
Is there a way to allow the empty field?
I want to validate the email field only if set

**Comment by equivalentideas** [comment]
@sarovin have a look at the [Conditional Validation section](http://guides.rubyonrails.org/active_record_validations.html#conditional-validation) of the [Active Record Validations guide](http://guides.rubyonrails.org/active_record_validations.html).

I don't think this is a relevant issue to this project and can be closed.

**Comment by alexdunae** [comment]
Agreed with @equivalentideas - [`allow_blank?`](https://guides.rubyonrails.org/active_record_validations.html#allow-blank) will do the trick.
