### ISSUE TITLE
"foo@bar.com--foo" is considered valid

### ISSUE THREAD

**Issue by maxkwallace** [validates-email-format-of/validates_email_format_of#64]
A question:
- Is this gem only meant to be spec-compliant, even if those specs don't handle all validation edge-cases?

If yes, then please keep a running list of those edge cases in the README. This would be very helpful so users of this gem are aware that the validation is not 100% comprehensive, nor is it intended to be.

If the validation is intended to be comprehensive, then this is a bug report :)-- "foo@bar.com--foo" is considered a valid email by `validates_email_format_of :email`.

**Comment by RST-J** [comment]
We just stumbled upon this, too. Maybe this should theoretically be covered by the Regexp and there is no anchors (\A, \z) which make sure that the pattern describe everything within the considered string?

**Comment by jufemaiz** [comment]
May be resolved by following RFC3639 and polling http://data.iana.org/TLD/tlds-alpha-by-domain.txt "frequently" for updates to TLD.

From 2003 today the list has blown out from 15 non-country TLDs to 1534.

**Comment by alexdunae** [comment]
Hello from 2022!  I'm spending a little time tidying things up.  I've started a [PR](https://github.com/validates-email-format-of/validates_email_format_of/pull/77) to deal with some of these parsing issues.

In this specific case, I think the TLD actually is valid (even though it's insane).  Per my reading https://tools.ietf.org/id/draft-liman-tld-names-00.html#rfc.section.2 the middle 61 characters of a domain "label" can be letters, digits or hyphens.  Unless I'm reading the RFC wrong, I believe `com--foo` is a syntactically valid TLD.

@jufemaiz it's an interesting point about grabbing the IANA TLD list.  My main concern is that it would get out of date over time and trigger false negatives, especially since IANA adds TLDs so frequently now

**Comment by jufemaiz** [comment]
Absolutely agree with that observation @alexdunae !

**Comment by maxkwallace** [comment]
> Unless I'm reading the RFC wrong, I believe com--foo is a syntactically valid TLD.

I 100% believe you. However, the reason I opened this issue is we had an actual user who did a typo and put a dash in their email address's TLD. This didn't get caught until we tried to email them and it bounced, at which point I had to deal with the error. I don't know of any commercial email providers that give out email addresses with dashes in the TLD.

So it begs the question: what's the value of complying strictly with the RFC if the RFC doesn't produce the expected/desired behavior in the wild?

I've maintained open source myself so I know it's a thankless job and you're probably not getting paid for this. I appreciate that this gem exists at all, and I'm grateful for the reply. Last thing I wanna do is demand you change the gem behavior because of my individual use case (& this was 6 years ago, I don't even work there anymore lol). 

But I thought it was worth opening an issue just because, as a user, when there are edge cases like this, I want to add an additional layer of validation on top of what the RFC says (even if I have to code it myself) so next time a user makes this mistake, it gets caught and I don't see it show up in our email error logs. I'd guess there are other devs who feel the same.

I was just thinking it would be nice to have these "gotchas" documented somewhere (e.g. in the README or in this issue) so it's less of a mystery when things go wrong.

**Comment by jufemaiz** [comment]
To be clear I think that any system that uses email as a primary key needs to confirm that:

1. it exists
2. the person who owns it confirms this is the case

This is just an additional validation step on input but shouldn't be relied upon for syntactically correct but incorrect insofar as spelling or similar.

**Comment by maxkwallace** [comment]
Yeah, as someone who consumes libraries like this, I also prefer not having network calls in data validation libraries. Options 2 and 3 both sound great!
