### ISSUE TITLE
Always defaulting to error message present in the config/locales present inside the gem. It is not considering the active model error messages mentioned in the config/locales inside the app

### ISSUE THREAD

**Issue by SakthiGurunathan07** [validates-email-format-of/validates_email_format_of#65]
In the below code it always override generate_message irrespective of whatever value passed.

```module ActiveModel
  module Validations
    class EmailFormatValidator < EachValidator
      def validate_each(record, attribute, value)
        (ValidatesEmailFormatOf::validate_email_format(value, options.merge(:generate_message => true)) || []).each do |error|
          record.errors.add(attribute, error)
        end
      end
    end`

**Comment by alexdunae** [comment]
Thank you for opening this issue in... um.... 2016.  No, that can't be right.

Can it?

Oh man.

Well... I hope the tiny dopamine hit you get when you get this notification overshadows the feeling of "WTF" you get when you check the timestamps on your original issue.

Thanks for your contribution.  Cheers from 2024 :)
