### ISSUE TITLE
Shorten timeout for DNS lookups

### ISSUE THREAD

**Issue by aripollak** [validates-email-format-of/validates_email_format_of#66]
The default timeout for Resolv::DNS results in the validation for an unresponsive domain (like test123.com) taking at least 20 seconds. I'd like to reduce the timeout in validates_email_format_of using [this](https://github.com/ruby/ruby/blob/32674b167bddc0d737c38f84722986b0f228b44b/lib/resolv.rb#L342-L355) since 20 seconds is way too long for a web request. Would you be okay with reducing the default timeout to 2 seconds with no retries (that would end up being 4 seconds total, one for A and one for MX)? Alternatively, validates_email_format_of can take an optional timeout number.

**Comment by kartikluke** [comment]
It should be a simple change. This function needs to take timeouts as well and we can have timeouts as an option to validates_email_format_of.

https://github.com/validates-email-format-of/validates_email_format_of/blob/14dd0630d21172e0a03128501a9380633226c6ff/lib/validates_email_format_of.rb#L14

```
def self.validate_email_domain(email, timeouts = 2)
    domain = email.to_s.downcase.match(/\@(.+)/)[1]
    Resolv::DNS.open do |dns|
        dns.timeouts = timeouts
        @mx = dns.getresources(domain, Resolv::DNS::Resource::IN::MX) + dns.getresources(domain, Resolv::DNS::Resource::IN::A)
    end
    @mx.size > 0 ? true : false
end
```

**Comment by atomical** [comment]
If it times out does it return invalid for the e-mail?

**Comment by alexdunae** [comment]
Good idea.  I've added that. 

If it times out a [`ResolvTimeout`](https://ruby-doc.org/stdlib-2.6.1/libdoc/resolv/rdoc/Resolv/ResolvTimeout.html) is thrown.
