### ISSUE TITLE
A few incorrect results

### ISSUE THREAD

**Issue by richdrich** [validates-email-format-of/validates_email_format_of#69]
Accepted incorrectly: 
Embedded double dots (RFC3696 page 5)

    wrong..local@bad.tv

Rejected incorrectly:
Comments https://tools.ietf.org/html/rfc5322#section-3.2.3
and see also https://productforums.google.com/forum/#!topic/gmail/aLIrqzbAY0k;context-place=topicsearchin/gmail/authorid$3AAPn2wQdJa7eCNs3J0n76qllhgltRI5gEUnxAfBt2tPmA0Inn75EjADYRvGoKZ96atlLfEl58f3Px%7Csort:date%7Cspell:false

    (leading comment)email@good.tv

Any character in quoted string:

    "Quote(Only".Chars@wier.de
    # or any of '(', ')', ',', ':', ';', '<', '>', '@', '[', ']'

I would agree that this is gross hair-splitting, but if you're aiming for complete RFC compliance? Also, like many others, my app wants to accept any emails that a user has managed to set up, as opposed to allowing users to create a new email.

**Comment by alexdunae** [comment]
Thanks for reporting this (five years ago!).   I'm doing a lap through trying to tighten up these loose ends.

Looking into the double periods, from my reading it appears [periods always need to be surrounded by `atext`](https://www.rfc-editor.org/rfc/rfc5322#section-3.2.3) 

` dot-atom-text   =   1*atext *("." 1*atext)`

... so consecutive periods would not be allowed.   

Email comments are wacky, but I've got support for them [added in a branch](https://github.com/validates-email-format-of/validates_email_format_of/pull/77) as well as the quoted characters being allowed in a quoted string.

Thanks for  filing the issue.  My goal is to get parsing 100% compliant and then figure out a more "realistic" mode users could opt-in to.
