### ISSUE TITLE
emails ending in \n are considered valid

### ISSUE THREAD

**Issue by ConfusedVorlon** [validates-email-format-of/validates_email_format_of#72]
e.g. `me@domain.com\n`

I don't know whether that's technically allowed, but it does cause an error in actionMailer

`ArgumentError: SMTP To address may not contain CR or LF line breaks: "xxx@gmail.com\n"`

**Comment by olleolleolle** [comment]
There is a part of the validator which does `email.strip`.

I'd like the validator not to do that.
