### ISSUE TITLE
Domains starting with numbers fail validation

### ISSUE THREAD

**Issue by ken-schwartz** [validates-email-format-of/validates_email_format_of#88]
Works in `1.6.3`
Fails in `1.7.x`

Email addresses with domains that start with numbers are failing validation. Below are some generic examples:
- `anything@123domain.com` -- INVALID in `1.7.x`, VALID in `1.6.3`
- `anything@domain123.com` -- VALID in all versions

Please let me know if there is any more information you need!

**Comment by alexdunae** [comment]
Thanks for reporting!
